name: Request doc changes
description: Report a problem or make a suggestion directly from a docs.netapp.com page using the Request doc changes link.
body:
  - type: markdown
    attributes:
      value: |
        Welcome and thank you for your contribution. 
        
        **Anything that you enter here is publicly visible.** If you need to provide sensitive information, you can email us at doccomments@netapp.com.
  - type: input
    id: page-url
    attributes:
      label: Page URL
    validations:
      required: true
  - type: input
    id: page-title
    attributes:
      label: Page title
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Summary 
      description: Required. Describe the problem. 
    validations:
      required: true
  - type: checkboxes
    id: terms-public
    attributes:
      label: Public issues must not contain sensitive information
      description: "Required. Examples of sensitive information include but are not limited to customer information, employee information, unreleased features, release dates, or confidential product information."
      options:
        - label: This issue contains no sensitive information. 
          required: true
