name: NetAppDocs Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run NetAppDocs production build
        run: echo Hello from NetAppDocs Organization
