name: NetAppDocs Build

on:
  push:
    branches:
      - '*'
      - '!main'
run-name: <<GHAPP_NAME>>

env:
  #New variables
  GH_APP_FLAG: true
  GH_APP_ID: <<GHAPP_ID>>
  GH_APP_REPOSITORY: <<GHAPP_REPOSITORY>>
  GH_APP_EVENT_NAME: <<GHAPP_EVENT_NAME>>
  GH_APP_HEAD_REF: <<GHAPP_BRANCH>>
  GH_APP_REGISTER_URL: <<GHAPP_REGISTER_URL>>
  GH_APP_SHA: <<GHAPP_REGISTER_SHA>>
  
  INTERNAL_FLAG: <<GHAPP_INTERNAL_FLAG>>
  
  RUN_ID: ${{ github.run_id }}
  NAME: ${{ github.workflow }}
  
  #Original
  DEPLOY_VERSION: v3
  FRAMEWORK_BRANCH: iebuild-bot
  
jobs:
  build:
    runs-on: ${{ github.event.inputs.internal == 'internal' && 'netappdocs-runner'  || 'ubuntu-20.04' }}
    steps:
      - name: Set check to in progress
        run: |
          curl -G "${{env.GH_APP_REGISTER_URL}}"\
            -d id=${{ env.GH_APP_ID }} \
            -d run_id=${{ env.RUN_ID }} \
            -d sha=${{ env.GH_APP_SHA }} \
            --data-urlencode "name=${{ env.NAME }}" \
        shell: bash
      
      - name: "Test Checkout"
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_APP_REPOSITORY }}
          token: ${{ env.GH_DEPLOY }}
          ref: ${{ env.GH_APP_HEAD_REF }}
             
