name: NetAppDocs Pull

on:
  repository_dispatch:
    types: [org-workflow-pull, org-workflow-push]  

run-name: ${{ github.event.client_payload.repository.name}}:${{ github.event.client_payload.repository.branch_name}} ${{ github.event.client_payload.repository.message}}

env:
  #New variables
  GH_APP_FLAG: true
  GH_APP_ID: ${{ github.event.client_payload.id }}
  GH_APP_REPOSITORY: ${{ github.event.client_payload.repository.full_name }}
  GH_APP_EVENT_NAME: ${{ github.event.client_payload.action.type }}
  GH_APP_HEAD_REF: ${{ github.event.client_payload.repository.ref }}
  GH_APP_REGISTER_URL: ${{ github.event.client_payload.register_url }}
  GH_APP_UPDATE_URL: ${{ github.event.client_payload.update_url }}
  GH_APP_SHA: ${{ github.event.client_payload.sha }}
  
  INTERNAL_FLAG: ${{ github.event.client_payload.action.internal }}
  GH_DEPLOY: ${{ github.event.client_payload.token }}
  
  RUN_ID: ${{ github.run_id }}
  NAME: ${{ github.workflow }}
  
  
        
jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ${{ github.event.client_payload.repository.internal && 'netappdocs-runner'  || 'ubuntu-20.04' }}
    steps:
      - name: Set check to in progress
        run: |
          curl -G "${{env.GH_APP_REGISTER_URL}}"\
            -d id=${{ env.GH_APP_ID }} \
            -d run_id=${{ env.RUN_ID }} \
            -d sha=${{ env.GH_APP_SHA }} \
            --data-urlencode "name=${{ env.NAME }}" \
        shell: bash
      - name: Test PR
        run: echo "Test PR"
        shell: bash
        
      - name: Adding markdown
        run: echo "### Hello world! ${{github.event.action}}" >> $GITHUB_STEP_SUMMARY
        
      - name: Adding markdown 2
        run: |
          echo '### Hello world! ' >> test.md
          echo '### Hello world 2! ' >> test.md
        
      - name: Update MD
        run: |
          cat test.md
          MARKDOWN_URI=$(cat test.md)
          echo $MARKDOWN_URI
          curl -G "${{env.GH_APP_UPDATE_URL}}"\
            -d id=${{ env.GH_APP_ID }} \
            -d run_id=${{ env.RUN_ID }} \
            -d sha=${{ env.GH_APP_SHA }} \
            --data-urlencode "name=${{ env.NAME }}" \
            --data-urlencode "summary=$MARKDOWN_URI" \
        shell: bash
        
      - name: Sleep for 1 minutes
        run: sleep 60s
        shell: bash

