name: NetAppDocs Build

on:
  repository_dispatch:
    types: [ org-workflow-push2, org-workflow-pull2 ]  

run-name: ${{ github.event.client_payload.repository.full_name}}/${{ github.event.client_payload.repository.ref}} ${{ github.event.client_payload.repository.message}}

env:
  #New variables
  GH_APP_FLAG: true
  GH_APP_ID: ${{ github.event.client_payload.id }}
  GH_APP_REPOSITORY: ${{ github.event.client_payload.repository.full_name }}
  GH_APP_EVENT_NAME: ${{ github.event.client_payload.event_name }}
  GH_APP_HEAD_REF: ${{ github.event.client_payload.ref }}
  GH_APP_REGISTER_URL: ${{ github.event.client_payload.register_url }}
  GH_APP_UPDATE_URL: ${{ github.event.client_payload.update_url }}
  GH_APP_SHA: ${{ github.event.client_payload.sha }}
  
  INTERNAL_FLAG: ${{ github.event.client_payload.internal }}
  GH_DEPLOY: ${{ github.event.client_payload.token }}
  
  RUN_ID: ${{ github.run_id }}
  NAME: ${{ github.workflow }}
  
  #Original
  DEPLOY_VERSION: v3
  FRAMEWORK_BRANCH: iebuild-bot
  
jobs:
  build:
    runs-on: ${{ github.event.inputs.internal == 'internal' && 'netappdocs-runner'  || 'ubuntu-20.04' }}
    steps:
      - name: Set check to in progress
        run: |
          curl -G "${{env.GH_APP_REGISTER_URL}}"\
            -d id=${{ env.GH_APP_ID }} \
            -d run_id=${{ env.RUN_ID }} \
            -d sha=${{ env.GH_APP_SHA }} \
            --data-urlencode "name=${{ env.NAME }}" \
        shell: bash
      
      - name: "Test Checkout"
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_APP_REPOSITORY }}
          token: ${{ env.GH_DEPLOY }}
          ref: ${{ env.GH_APP_HEAD_REF }}
      
      - name: Adding markdown 2
        run: echo "### Generating content for ${{env.GH_APP_EVENT_NAME}} " >> test.md
        
      - name: Update MD
        run: |
          cat test.md
          MARKDOWN_URI=$(cat test.md)
          echo $MARKDOWN_URI
          curl -G "${{env.GH_APP_UPDATE_URL}}"\
            -d id=${{ env.GH_APP_ID }} \
            -d run_id=${{ env.RUN_ID }} \
            -d sha=${{ env.GH_APP_SHA }} \
            --data-urlencode "name=${{ env.NAME }}" \
            --data-urlencode "summary=$MARKDOWN_URI" \
        shell: bash

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
    
